dist: xenial

language: python

python:
  - 2.7.16

before_install:
  - cp test/secrets.mock secrets.yaml

install:
  - pip install yamllint
  - pip install esphome
  - pip install voluptuous==0.11.5

script:
  - yamllint .
  - . test/test.sh
