esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

substitutions:
  device_name: sensor_ath_1

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version

status_led:
  pin: GPIO2

mqtt: # Not compatible with the api config
  broker: mqtt.home.d6e.io
  discovery: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: false

      #mqtt: # Not compatible with the api config
  #  broker: homeassistant.local
  #  discovery: True

logger:

switch:
  - platform: restart
    name: ${device_name}_Restart

sensor:
  - platform: dht
    pin: GPIO23
    temperature:
      name: ${device_name} Temperature
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
        - lambda: return x * (9.0/5.0) + 32.0; # report temperature in Fahrenheit
      unit_of_measurement: "°F"
    humidity:
      name: ${device_name} Humidity
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
      accuracy_decimals: 1        # humidity gets 0 decimals by default
    model: DHT11
    update_interval: 60s
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
  - platform: wifi_signal
    name: ${device_name}_rssi
    update_interval: 60s

# https://esphome.io/components/sensor/pmsx003.html

uart:
  rx_pin: GPIO22
  baud_rate: 9600
