substitutions:
  device_name: test_pir

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  # board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: false

      #mqtt: # Not compatible with the api config
  #  broker: homeassistant.local
  #  discovery: True

logger:

api: # Not compatible with the MQTT config
  password: !secret esphome_api_pwd

ota:
  password: !secret esphome_ota_pwd

switch:
  - platform: restart
    name: ${device_name}_Restart

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "PIR Sensor"
    device_class: motion

sensor:
  - platform: wifi_signal
    name: ${device_name}_rssi
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version

status_led:
  pin: GPIO2
